### ISSUE TITLE
npm ERR! code E404

### ISSUE THREAD

**Issue by amnweb** [paidless/videojs-yt-style#1]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/videojs-yt-style - Not found
npm ERR! 404
npm ERR! 404  'videojs-yt-style@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by Ami-OS** [comment]
Sorry, this is a highly early project, I just uploaded it to npm, it should be working.
And I also update the [README](https://github.com/paidless/videojs-yt-style) file, you can find more in that.
